### ISSUE TITLE
Getting dependency lock error when following provider tutorial

### ISSUE THREAD

**Issue by Coockson** [hashicorp/terraform-provider-hashicups#132]
While following the documentation step by step in the [tutorial](https://developer.hashicorp.com/terraform/tutorials/providers-plugin-framework/providers-plugin-framework-provider), I get the following error:

```
╷
│ Warning: Provider development overrides are in effect
│ 
│ The following provider development overrides are set in the CLI configuration:
│  - hashcorp.com/edu/hashicups in /Users/myname/go/bin
│ 
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible
│ with published releases.
╵
╷
│ Error: Inconsistent dependency lock file
│ 
│ The following dependency selections recorded in the lock file are inconsistent with the current configuration:
│   - provider hashicorp.com/edu/hashicups: required by this configuration but no version is selected
│ 
│ To make the initial dependency selections that will initialize the dependency lock file, run:
│   terraform init
```

I expect to get the `Error: Invalid data source` error instead, as the documentation suggests. 
So it does detect the development override, and it is pointing at my go directory. I can see the go provider in that directory.

Pinging @bflad as I saw he responded to a similar issue.

**Comment by robin-norwood** [comment]
This happens when the developer overrides aren't set up successfully as [described here](https://developer.hashicorp.com/terraform/tutorials/providers-plugin-framework/providers-plugin-framework-provider#prepare-terraform-for-local-provider-install).

Double check that:

- The `.terraformrc` file includes the `dev_overrides` for hashicups, with the correct path based on your system type and `GOBIN` environment var, if any.
- The path to your GOBIN is correct and exists.
- The `go install .` command was successful, and that the `terraform-provider-hashicups` file exists in the above go bin directory..
