### ISSUE TITLE
Tutorial issue with HASHICUPS_TOKEN

### ISSUE THREAD

**Issue by motatoes** [hashicorp/terraform-provider-hashicups#40]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

There is an inaccuracy in the tutorial:  https://learn.hashicorp.com/tutorials/terraform/provider-use

it mentions to export the token prior to terraform apply as follows:

```
export HASHICUPS_TOKEN=ey...
```

However following this guide leads to the following error:

```
hashicups_order.edu: Creating...

Error: status: 401, body: token contains an invalid number of segments
```

The tutorial should instead guide us to export the username and the password as follows for the provider to use it:

```
export HASHICUPS_USERNAME=education
export HASHICUPS_PASSWORD=test123 
```

**Comment by im2nguyen** [comment]
Hey @motatoes, thanks for reporting this.

The HashiCups token is used later in the tutorial to verify Terraform created the resources. For example, you can see it in the end of "[Verify order created](https://learn.hashicorp.com/tutorials/terraform/provider-use#verify-order-created)". It's similarly used after order update and deletion.

```
$ curl -X GET  -H "Authorization: ${HASHICUPS_TOKEN}" localhost:19090/orders/1
```

I'm not sure why you received that error. It might be because the user didn't exist? If you used the configuration provided in the "[Create order](https://learn.hashicorp.com/tutorials/terraform/provider-use#create-order)" it should work if you created the user successfully. The user credentials are hardcoded in the provider configuration itself. As a result, you don't need to export the username and password.

```
provider "hashicups" {
  username = "education"
  password = "test123"
}
```

Please let me know if you have any questions or if I misunderstood your question. Have a good one!

**Comment by motatoes** [comment]
hi @im2nguyen I'm sorry about this false report after review I saw that I missed copying that `provider` block over to my main.tf. Thanks!

**Comment by rheathcote-deloitte** [comment]
I got caught by this - that provider block is really easy to miss. I've been using the terraform azure provider in production code, and now I'm trying to figure out provider development. Coming from that perspective, it seems quite bad to put credentials IN a terraform file, even if it's a development thing. Azure uses the ARM_SAS_TOKEN to credential the state, I was so used to that workflow that once I set the HASHICUPS_TOKEN variable I thought it would just work. 

I would request (and may make a PR to this effect) that the provider block be given its own section with a paragraph explaining it.
