### ISSUE TITLE
Acceptance testing section assumes hard coded values

### ISSUE THREAD

**Issue by boeboe** [hashicorp/terraform-provider-hashicups#98]
The testing section of the tutorial contains hard coded values in terms of what to expect as a return from the hashicups api.

```golang
            {
                Config: providerConfig + `data "hashicups_coffees" "test" {}`,
                Check: resource.ComposeAggregateTestCheckFunc(
                    // Verify number of coffees returned
                    resource.TestCheckResourceAttr("data.hashicups_coffees.test", "coffees.#", "9"),
                    // Verify the first coffee to ensure all attributes are set
                    resource.TestCheckResourceAttr("data.hashicups_coffees.test", "coffees.0.description", ""),
                    resource.TestCheckResourceAttr("data.hashicups_coffees.test", "coffees.0.id", "1"),
                    resource.TestCheckResourceAttr("data.hashicups_coffees.test", "coffees.0.image", "/hashicorp.png"),
                    resource.TestCheckResourceAttr("data.hashicups_coffees.test", "coffees.0.ingredients.#", "1"),
                    resource.TestCheckResourceAttr("data.hashicups_coffees.test", "coffees.0.ingredients.0.id", "6"),
                    resource.TestCheckResourceAttr("data.hashicups_coffees.test", "coffees.0.name", "HCP Aeropress"),
                    resource.TestCheckResourceAttr("data.hashicups_coffees.test", "coffees.0.price", "200"),
                    resource.TestCheckResourceAttr("data.hashicups_coffees.test", "coffees.0.teaser", "Automation in a cup"),
                    // Verify placeholder id attribute
                    resource.TestCheckResourceAttr("data.hashicups_coffees.test", "id", "placeholder"),
                ),
            },
```

Is one supposed to prefil the API with 9 coffees, where the first has the values as hard coded in the above test case? Shouldn't there be some pre-run step that populates the hashicops coffee objects in the REST API, before the acceptance tests are running? What is your recommendation to achieve acceptance tests that will work on a pre-populated dataset?

**Comment by bflad** [comment]
Hi @boeboe 👋 

The hashicups API should already be pre-filled with data in its database within the Docker container. If that is not true, please let us know.

> What is your recommendation to achieve acceptance tests that will work on a pre-populated dataset?

The best place to ask questions about provider development and testing is [HashiCorp Discuss](https://discuss.hashicorp.com/c/terraform-providers/tf-plugin-sdk/43), where there are more provider developers able to assist rather than this GitHub repository issue tracker which is only monitored by a few maintainers.

This specific use case likely requires a little bit more detail about the background of the problem before being answered, but there are potentially some features within Terraform and the terraform-plugin-testing Go module which can help. If you are looking for generating testing code, Terraform and terraform-plugin-testing accept [JSON configurations](https://developer.hashicorp.com/terraform/language/syntax/json). This may enable you to automatically generate data source configurations to reference specific values from a pre-defined dataset. Terraform 1.2 and later also implement [`postcondition` configuration blocks](https://developer.hashicorp.com/terraform/language/expressions/custom-conditions#preconditions-and-postconditions) which would be an alternative way to declare value assertions within the configuration directly, rather than being dependent on Go programming language code value checks. It might be possible to combine these two concepts in your situation to automate testing.

If you have further questions about this, please follow up in HashiCorp Discuss. Since this GitHub issue represents a question rather than a bug report or feature request of this tutorial provider, I'm going to close the issue.
